#!/bin/bash
##############################################################################
# Copyright (c) 2014 Behan Webster
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
##############################################################################

# Meant to be used as an external diff to git for seeing whether patches
# have changed when being sent through git back to quilt.
# We don't care if the "^From " line has changed, or the version of git

diff --suppress-common-lines --text --unified=0 \
	<(sed -r '/^From /d; /^index [0-9a-f]{7}\.{2}[0-9a-f]{7} [0-9]+$/d; /^([0-9]+\.){2,3}[0-9]/d; /^\@\@ /d' $1) \
	<(sed -r '/^From /d; /^index [0-9a-f]{7}\.{2}[0-9a-f]{7} [0-9]+$/d; /^([0-9]+\.){2,3}[0-9]/d; /^\@\@ /d' $2)
